name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run install dependenies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build app
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Copy index.html to public
        run: cp ./index.html ./public
      
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./public
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
